use_frameworks!

target 'ALWPageControl_Example' do
  pod 'ALWPageControl', :path => '../'

  target 'ALWPageControl_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
